{{- if .Values.newrelic.deploy -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bazo.newrelic.name" . }}
  labels:
    {{- include "bazo.newrelic.labels" . | nindent 4 }}
spec:
  {{- if not .Values.newrelic.autoscaling.enabled }}
  replicas: {{ .Values.newrelic.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bazo.newrelic.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/cms/configmap.yaml") . | sha256sum }}
        {{- with .Values.newrelic.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "bazo.newrelic.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bazo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.newrelic.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.newrelic.securityContext | nindent 12 }}
          image: "{{ .Values.newrelic.image.repository }}:{{ .Values.newrelic.image.tag }}"
          imagePullPolicy: {{ .Values.newrelic.image.pullPolicy }}
          ports:
            - name: newrelic-daemon
              containerPort: 31339
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 31339
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 31339
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.newrelic.resources | nindent 12 }}
      {{- with .Values.newrelic.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.newrelic.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.newrelic.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}