apiVersion: v1
kind: Service
metadata:
  name: {{ include "bazo.cms.name" . }}
  labels:
    {{- include "bazo.cms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.cms.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bazo.cms.selectorLabels" . | nindent 4 }}