apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bazo.admin.php.name" . }}
  labels:
    {{- include "bazo.admin.labelsPHP" . | nindent 4 }}
spec:
  {{- if not .Values.admin.php.autoscaling.enabled }}
  replicas: {{ .Values.admin.php.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bazo.admin.selectorLabelsPHP" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/common/configmap.yaml") . | sha256sum }}
        {{- with .Values.admin.php.podAnnotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "bazo.admin.selectorLabelsPHP" . | nindent 8 }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bazo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.admin.php.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.admin.php.securityContext | nindent 12 }}
          image: "{{ .Values.admin.php.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.admin.php.image.pullPolicy }}
          ports:
            - name: php-fpm
              containerPort: 9000
              protocol: TCP
          envFrom:
            - prefix: ''
              configMapRef:
                name: {{ include "bazo.configmap" . }}
          {{- if .Values.newrelic.deploy }}
          volumeMounts:
            - mountPath: /usr/local/etc/php/conf.d/newrelic.ini
              name: vol1
              subPath: newrelic.ini
          {{- end }}
          livenessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.admin.php.resources | nindent 12 }}
      {{- if .Values.newrelic.deploy }}
      volumes:
        - configMap:
            defaultMode: 256
            items:
              - key: newrelic.ini
                mode: 511
                path: newrelic.ini
            name: {{ include "bazo.newrelic.name" . }}-php-config
            optional: false
          name: vol1
      {{- end }}
      {{- with .Values.admin.php.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admin.php.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admin.php.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bazo.admin.web.name" . }}
  labels:
    {{- include "bazo.admin.labelsWeb" . | nindent 4 }}
spec:
  {{- if not .Values.admin.nginx.autoscaling.enabled }}
  replicas: {{ .Values.admin.nginx.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bazo.admin.selectorLabelsWeb" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.admin.nginx.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bazo.admin.selectorLabelsWeb" . | nindent 8 }}
    spec:
      {{- with .Values.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bazo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.admin.nginx.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.admin.nginx.securityContext | nindent 12 }}
          image: "{{ .Values.admin.nginx.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.admin.nginx.image.pullPolicy }}
          env:
            - name: FPM_HOST
              value: {{ include "bazo.admin.php.name" . }}:{{ .Values.admin.php.service.port }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 80
          readinessProbe:
            tcpSocket:
              port: 80
          resources:
            {{- toYaml .Values.admin.nginx.resources | nindent 12 }}
      {{- with .Values.admin.nginx.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admin.nginx.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admin.nginx.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
