apiVersion: v1
kind: Service
metadata:
  name: {{ include "bazo.admin.php.name" . }}
  labels:
    {{- include "bazo.admin.labelsPHP" . | nindent 4 }}
spec:
  type: {{ .Values.admin.php.service.type }}
  ports:
    - port: {{ .Values.admin.php.service.port }}
      targetPort: 9000
      protocol: TCP
      name: php-fpm
  selector:
    {{- include "bazo.admin.selectorLabelsPHP" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bazo.admin.web.name" . }}
  labels:
    {{- include "bazo.admin.labelsWeb" . | nindent 4 }}
spec:
  type: {{ .Values.admin.nginx.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bazo.admin.selectorLabelsWeb" . | nindent 4 }}