apiVersion: v1
kind: Service
metadata:
  name: {{ include "bazo.cdn.php.name" . }}
  labels:
    {{- include "bazo.cdn.labelsPHP" . | nindent 4 }}
spec:
  type: {{ .Values.cdn.php.service.type }}
  ports:
    - port: {{ .Values.cdn.php.service.port }}
      targetPort: 9000
      protocol: TCP
      name: php-fpm
  selector:
    {{- include "bazo.cdn.selectorLabelsPHP" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bazo.cdn.web.name" . }}
  labels:
    {{- include "bazo.cdn.labelsWeb" . | nindent 4 }}
spec:
  type: {{ .Values.cdn.nginx.service.type }}
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bazo.cdn.selectorLabelsWeb" . | nindent 4 }}